baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-katex'

[module]
  replacements = 'github.com/markdumay/mod-katex -> ../..'
  [[module.imports]]
    path = "github.com/markdumay/mod-katex"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"